name: Publish
on:
  push:
    branches:
      - main
    paths:
      - ".github/**"
      - "src/**"
      - "README.md"
      - "package.json"
      - "tsconfig.json"
      - ".npmrc"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
        with:
          registry-url: "https://registry.npmjs.org"
      - run: bun install
      - run: bun test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - run: bun run build
      - run: bun publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
